name: goeng
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  html: ^0.15.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/page-1/images/line-2.png
    - assets/page-1/images/icon-magnifying-glass.png
    - assets/page-1/images/frame-4.png
    - assets/page-1/images/icon-house.png
    - assets/page-1/images/icon-user-circle.png
    - assets/page-1/images/auto-group-cdec.png
    - assets/page-1/images/icon-user-circle-nrg.png
    - assets/page-1/images/icon-house-Xsi.png
    - assets/page-1/images/auto-group-egmj.png
    - assets/page-1/images/auto-group-qnfv.png
