name: goeng
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  html: ^0.15.0
  google_fonts: ^4.0.4
  mongo_dart: ^0.10.0
  dart_jsonwebtoken: 2.12.1
  meta: ^1.7.0
  dartx: ^0.7.0
  shared_preferences: 2.2.2
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/page-1/images/icon-magnifying-glass.png
    - assets/page-1/images/2.png
    - assets/page-1/images/icon-user-circle.png
    - assets/page-1/images/-g28.png
    - assets/page-1/images/line-2.png
    - assets/page-1/images/icon-house.png
